version: "3"

volumes:
  php-fpm-socket:
  #db-store:

services:
  web:
    image: sso-redirect-examples/web:develop
    ports:
      - ${WEB_PORT:-3070}:80
    expose:
      - ${WEB_PORT:-3070}
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ./deploy/docker/auth-client/nginx-node/local/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - client

  client:
    image: sso-redirect-examples/client:develop
    volumes:
      - php-fpm-socket:/var/run/php-fpm
    environment:
      - APP_NAME_C=${APP_NAME_C}
      - APP_ENV_C=${APP_ENV_C}
      - APP_KEY_C=${APP_KEY_C}
      - APP_DEBUG_C=${APP_DEBUG_C}
      - APP_URL_C=${APP_URL_C}
      - AWS_COGNITO_DOMAIN_PREFIX_C=${AWS_COGNITO_DOMAIN_PREFIX_C}
      - AWS_COGNITO_REGION_C=${AWS_COGNITO_REGION_C}
      - AWS_COGNITO_CLIENT_ID_C=${AWS_COGNITO_CLIENT_ID_C}
      - AWS_COGNITO_CLIENT_SECRET_C=${AWS_COGNITO_CLIENT_SECRET_C}
      - AWS_COGNITO_USER_POOL_ID_C=${AWS_COGNITO_USER_POOL_ID_C}
