version: "3"

services:
  web:
    image: sso-redirect-examples/web:develop
    ports:
      - ${WEB_PORT:-3070}:80
    expose:
      - ${WEB_PORT:-3070}
    volumes:
      - ./deploy/docker/auth-client/nginx-node/local/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - client

  client:
    image: sso-redirect-examples/client:develop
    environment:
      - APP_NAME=${APP_NAME_C}
      - APP_ENV=${APP_ENV_C}
      - APP_KEY=${APP_KEY_C}
      - APP_DEBUG=${APP_DEBUG_C}
      - APP_URL=${APP_URL_C}
      - AWS_COGNITO_DOMAIN_PREFIX=${AWS_COGNITO_DOMAIN_PREFIX_C}
      - AWS_COGNITO_REGION=${AWS_COGNITO_REGION_C}
      - AWS_COGNITO_CLIENT_ID=${AWS_COGNITO_CLIENT_ID_C}
      - AWS_COGNITO_CLIENT_SECRET=${AWS_COGNITO_CLIENT_SECRET_C}
      - AWS_COGNITO_USER_POOL_ID=${AWS_COGNITO_USER_POOL_ID_C}
