region: ap-northeast-1
cluster: dev-sso-examples-ecs-cluster
service: auth-client
service_definition: ecs-service-def.json
task_definition: ecs-task-def.json
timeout: 5m
plugins:
  - name: tfstate
    config:
      url: # Set Your tfstate URL
      #path: ../../terraform.tfstate
appspec: null
