version: "3"

volumes:
  php-fpm-socket:
  db-store:

services:
  client:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ../../applications/auth-client:/work
    environment:
      - APP_NAME_C=${APP_NAME_C}
      - APP_ENV_C=${APP_ENV_C}
      - APP_KEY_C=${APP_KEY_C}
      - APP_DEBUG_C=${APP_DEBUG_C}
      - APP_URL_C=${APP_URL_C}
      - AWS_COGNITO_DOMAIN_PREFIX_C=${AWS_COGNITO_DOMAIN_PREFIX_C}
      - AWS_COGNITO_REGION_C=${AWS_COGNITO_REGION_C}
      - AWS_COGNITO_CLIENT_ID_C=${AWS_COGNITO_CLIENT_ID_C}
      - AWS_COGNITO_CLIENT_SECRET_C=${AWS_COGNITO_CLIENT_SECRET_C}
      - AWS_COGNITO_USER_POOL_ID_C=${AWS_COGNITO_USER_POOL_ID_C}
      - DB_HOST_C=${DB_HOST_C}
      - DB_NAME_C=${DB_NAME_C}
      - DB_USER_C=${DB_USER_C}
      - DB_PASS_C=${DB_PASS_C}
      - REDIS_HOST_C=${REDIS_HOST_C}

  web:
    build:
      context: .
      dockerfile: ./docker/nginx-node/Dockerfile
    ports:
      - ${WEB_PORT:-3070}:80
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ../../applications/auth-client:/work

  db:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
      args:
        - TZ=Asia/Tokyo
    ports:
      - ${DB_EXPOSE_PORT_C:-3306}:3306
    volumes:
      - db-store:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME_C}
      - MYSQL_USER=${DB_USER_C}
      - MYSQL_PASSWORD=${DB_PASS_C}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS_C}

  redis:
    build:
      context: .
      dockerfile: ./docker/redis/Dockerfile
      args:
        - TZ=Asia/Tokyo
