version: "3"

volumes:
  php-fpm-socket:
  db-store:

services:
  client:
    build:
      context: .
      dockerfile: ./docker/auth-client/php/Dockerfile
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ../../applications/auth-client:/work
    environment:
      - APP_NAME=${APP_NAME}
      - APP_ENV=${APP_ENV}
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=${APP_DEBUG}
      - APP_URL=${APP_URL}
      - AWS_COGNITO_REGION=${AWS_COGNITO_REGION}
      - AWS_COGNITO_CLIENT_ID=${AWS_COGNITO_CLIENT_ID}
      - AWS_COGNITO_CLIENT_SECRET=${AWS_COGNITO_CLIENT_SECRET}
      - AWS_COGNITO_USER_POOL_ID=${AWS_COGNITO_USER_POOL_ID}

  web:
    build:
      context: .
      dockerfile: ./docker/auth-client/nginx-node/Dockerfile
    ports:
      - ${WEB_PORT:-3070}:80
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ../../applications/auth-client:/work
